### ISSUE TITLE
Blocking Touch

### ISSUE THREAD

**Issue by indivisable** [glepur/react-native-swipe-gestures#1]
Does this terminate the touch? It seems that if you put a button inside the GestureRecognizer it stops working.

**Comment by glepur** [comment]
Confirmed, this is bug. Probably because bad configuration of `PanResponder`.

My guess is that `onStartShouldSetPanResponder` and `onMoveShouldSetPanResponder` should return `false` if event target is child element, and `onMoveShouldSetPanResponder` should be used to capture gesture state.

I'll dig into this when I get some free time. Also, if you figure it out I'd be glad to accept pull request.
